############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

accept-terms-of-use: true
enable-builder: true  # if use MEV-boost

##############
# Connectivity
beacon-rpc-provider: 127.0.0.1:4000
monitoring-host: 0.0.0.0
monitoring-port: 8081

#########
# Web-UI
#web: yes

#####################################
# Validator database, accounts & key management
datadir: /data
wallet-dir: /wallet
wallet-password-file: /run/secrets/wallet-password

###########
# 文字を入れると刻印を刻める
graffiti: ""

### EL報酬振込先、あなたのウォレットを指定する
# suggested-fee-recipient: 0x..........
