version: '3.7'
services:  
  mev:
    image: flashbots/mev-boost:1.6
    container_name: mev-boost
    command: >
      -goerli
      -addr
      0.0.0.0:18550
      -relay-check
      -relays
      https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@builder-relay-goerli.flashbots.net
    ports:
      - "18550:18550"
    env_file:
      - '.env'

    restart: always

