version: '3.7'
services:
  ######################
  ### eth1 #############
  ######################
  geth:
    # https://github.com/ethereum/go-ethereum/blob/master/Dockerfile
    image: ethereum/client-go:v1.12.2
    container_name: ethereum-node
    command: >
      --goerli --http --http.addr 0.0.0.0 --http.vhosts \* --metrics --metrics.addr 0.0.0.0 --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts \* --authrpc.jwtsecret /run/secrets/jwtsecret
    ports:
      - "6060:6060" # for metrics
      - "8551:8551" # rpc with auth 
      - "30303:30303"
      - "30303:30303/udp"
    env_file:
      - '.env'
    volumes:
      # Data persistency
      - ./storage.d/eth1:/root
    restart: always
    secrets:
      - jwtsecret
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

  
  ######################
  ### eth2 #############
  ######################
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.8
    container_name: beacon-node
    command: >
      --goerli 
      --config-file=/config/beacon.yaml
    ports:
      - "4000:4000" # for validators
      - "8080:8080" # for metrics, change port.
      - "12000:12000/udp"
      - "13000:13000"
    env_file:
      - '.env'
    restart: always
    secrets:
      - jwtsecret
    
    volumes:
      # Data persistency
      - ./storage.d/eth2:/data
      - ./conf.d/eth2:/config:ro
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

  
  ######################
  ### MEV-boost ########
  ######################
  mev:
    image: flashbots/mev-boost:1.6
    container_name: mev-boost
    command: >
      -goerli
      -addr
      0.0.0.0:18550
      -relay-check
      -relays
      https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@builder-relay-goerli.flashbots.net
    env_file:
      - '.env'
    restart: always
    
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

secrets:
  jwtsecret:
    file: ./jwtsecret
  