version: '3.7'
services:
  ######################
  ### eth1 #############
  ######################
  geth:
    # https://github.com/ethereum/go-ethereum/blob/master/Dockerfile
    image: ethereum/client-go:${TAG_ETH1:-v1.12.2}
    container_name: ethereum-node
    command: >
      --${NETWORK:-mainnet} --http --http.addr 0.0.0.0 --http.vhosts \* --metrics --metrics.addr 0.0.0.0 --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts \* --authrpc.jwtsecret /run/secrets/jwtsecret
    ports:
      - "6060:6060" # for metrics
      - "8551:8551" # rpc with auth 
      - "30303:30303"
      - "30303:30303/udp"
    env_file:
      - '.node.env'
    volumes:
      # Data persistency
      - eth1-storage:/root
    restart: always
    secrets:
      - jwtsecret
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

  
  ######################
  ### eth2 #############
  ######################
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${TAG_ETH2:-v4.0.8}
    container_name: beacon-node
    command: >
      --${NETWORK:-mainnet} 
      --config-file=/config/beacon.yaml
    ports:
      - "4000:4000" # for validators
      - "8080:8080" # for metrics, change port.
      - "12000:12000/udp"
      - "13000:13000"
    env_file:
      - '.node.env'
    restart: always
    secrets:
      - jwtsecret
    
    volumes:
      # Data persistency
      - eth2-storage:/data
      - ./conf.d/eth2:/config:ro
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

  
  ######################
  ### MEV-boost ########
  ######################
  mev:
    image: flashbots/mev-boost:${TAG_MEV_BOOST:-1.6}
    container_name: mev-boost
    command: >
      -${NETWORK:-mainnet}
      -addr
      0.0.0.0:18550
      -relay-check
      -relays
      ${URL_MEV_RELAY:-https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net}
    env_file:
      - '.node.env'
    restart: always
    
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-northeast-3
    #    awslogs-group: ethereum-node
    #    tag: "{{.Name}}/{{.ID}}"

volumes:
  eth1-storage:
  eth2-storage:

secrets:
  jwtsecret:
    file: ./jwtsecret
  